version: '3'

services:
  kyleangusdotcom:
    container_name: kangus/kyleangusdotcom:latest
    hostname: kyleangusdotcom
    restart: unless-stopped
    networks:
      - proxy-internal

  cornerstone:
    container_name: cornerstone
    image: kangus/cornerstone:latest
    hostname: cornerstone
    restart: unless-stopped
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASS: ${MYSQL_PASS}
      MYSQL_DB: ${MYSQL_DB}
      RADARR_HOST: ${RADARR_HOST}
      RADARR_KEY: ${RADARR_KEY}
    volumes:
      - /data:/data
    networks:
      - requires-outbound
      - proxy-internal

  brenbot-discord:
    container_name: brenbot-discord
    image: kangus/brenbot-discord:latest
    hostname: brenbot-discord
    restart: unless-stopped
    environment:
      PORT: 80
      PUBLIC_KEY: ${DISCORD_PUBLIC_KEY}
      DISCORD_TOKEN: ${DISCORD_TOKEN}
    networks:
      - requires-outbound
      - proxy-internal

  evictions-api:
    container_name: evictions-api
    image: kangus/evictions-api:latest
    hostname: evictions-api
    restart: unless-stopped
    environment:
      MARIADB_URL: ${MARIADB_URL}
      MARIADB_PORT: ${MARIADB_PORT}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      JWT_SECRET: ${JWT_SECRET}
      SEND_GRID_KEY: ${SEND_GRID_KEY}
      SEND_GRID_MAIL_FROM: ${SEND_GRID_MAIL_FROM}
      GOOGLE_MAPS_API_KEY: ${GOOGLE_MAPS_API_KEY}
      CLIENT_BASE_URL: ${CLIENT_BASE_URL}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
    networks:
      - requires-outbound
      - proxy-internal

  evictions-ui:
    container_name: evictions-ui
    image: kangus/evictions-ui:latest
    hostname: evictions-ui
    restart: unless-stopped
    environment:
      REACT_APP_API_PROXY: ${REACT_APP_API_PROXY}
    networks:
      - proxy-internal

networks:
  requires-outbound:
    external: true
  proxy-internal:
    external: true
