version: "3"

services:
  brenbot-discord:
    container_name: brenbot-discord
    image: kangus/brenbot-discord:latest
    hostname: brenbot-discord
    restart: unless-stopped
    environment:
      PORT: 80
      PUBLIC_KEY: ${DISCORD_PUBLIC_KEY}
      DISCORD_TOKEN: ${DISCORD_TOKEN}
    networks:
      - proxy-internal

networks:
  proxy-internal:
    external: true
