version: "3"

services:
  brenbot-discord:
    container_name: brenbot-discord
    image: kangus/brenbot-discord:latest
    hostname: brenbot-discord
    restart: unless-stopped
    environment:
      PORT: 80
      PUBLIC_KEY: ${DISCORD_PUBLIC_KEY}
      DISCORD_TOKEN: ${DISCORD_TOKEN}
    networks:
      - requires-outbound
      - proxy-internal

  evictions-api:
    container_name: evictions-api
    image: kangus/evictions-api:latest
    hostname: evictions-api
    restart: unless-stopped
    environment:
      SEND_GRID_KEY: ${SEND_GRID_KEY}
      SEND_GRID_MAIL_FROM: ${SEND_GRID_MAIL_FROM}
      RESET_PASSWORD_TEMPLATE: ${RESET_PASSWORD_TEMPLATE}
      MONGO_URL: ${MONGO_URL}
    networks:
      - proxy-internal

  evictions-ui:
    container_name: evictions-ui
    image: kangus/evictions-ui:latest
    hostname: evictions-ui
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      REACT_APP_API_PROXY: ${REACT_APP_API_PROXY}
    networks:
      - proxy-internal

networks:
  requires-outbound:
    external: true
  proxy-internal:
    external: true
