# project_zomboid_server:
#   container_name: project-zomboid-server
#   image: cyrale/project-zomboid:latest
#   restart: unless-stopped
#   environment:
#     SERVER_NAME: "zombieland"
#     ADMIN_PASSWORD: ${ZOMBOID_ADMIN_PASS}
#   volumes:
#     - /data/project-zomboid:/server-data
#   networks:
#     lan:
#       ipv4_address: 10.1.7.33
#   ports:
#     - "8766:8766/udp"
#     - "8767:8767/udp"
#     - "16261:16261/udp"
#     - "16262-16272:16262-16272"
#     - "27015:27015"

# factorio_server:
#   container_name: factorio-server
#   image: factoriotools/factorio:latest
#   restart: unless-stopped
#   environment:
#     INSTANCE_NAME: "Kangus' Megafactory"
#     INSTANCE_DESC: "Death to bugs"
#   volumes:
#     - /data/factorio:/factorio
#   networks:
#     lan:
#       ipv4_address: 10.1.7.34
#   ports:
#     - "34197:34197/udp"
#     - "27015:27015/tcp"

# runescape_classic_server:
#   container_name: runescape-classic-server
#   image: kangus/runescape-classic-server:latest
#   restart: unless-stopped
#   networks:
#     lan:
#       ipv4_address: 10.1.7.36
#   ports:
#     - "43594:43594"

