version: "3"

services:
  plex:
    container_name: plex
    hostname: plex.kangus.net
    image: plexinc/pms-docker:latest
    restart: unless-stopped
    environment:
      TZ: "America/Detroit"
      PLEX_CLAIM: ${PLEX_CLAIM}
    volumes:
      - plex:/config
      - plex:/transcode
      - /media:/media
    networks:
      proxy-traffic:
      lan:
        ipv4_address: 10.1.7.5

  plex_metrics:
    container_name: plex-metrics
    hostname: plex-metrics
    image: tautulli/tautulli
    restart: unless-stopped
    environment:
      TZ: "America/Detroit"
    volumes:
      - plex-metrics:/config
    networks:
      - proxy-traffic

  utorrent:
    container_name: utorrent
    image: ekho/utorrent:legacy
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      TZ: "America/Detroit"
      PUID: 1000
      PGID: 1000
    volumes:
      - utorrent:/utorrent/settings
      - /media/torrent:/data
    networks:
      proxy-traffic:
      lan:
        ipv4_address: 10.1.7.6

  nzbet:
    container_name: nzbget
    image: linuxserver/nzbget
    restart: unless-stopped
    environment:
      TZ: "America/Detroit"
      NZBGET_USER: nzbget
      NZBGET_PASS: ${NZBGET_PASS}
      PUID: 1000
      PGID: 1000
    volumes:
      - nzbget:/config
      - /media:/data
    networks:
      - proxy-traffic

  radarr:
    container_name: radarr
    image: linuxserver/radarr
    restart: unless-stopped
    environment:
      TZ: "America/Detroit"
      PUID: 1000
      PGID: 1000
    volumes:
      - radarr:/config
      - /media:/data
    networks:
      - proxy-traffic

  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr
    restart: unless-stopped
    environment:
      TZ: "America/Detroit"
      PUID: 1000
      PGID: 1000
    volumes:
      - sonarr:/config
      - /media:/data
    networks:
      - proxy-traffic

  jackett:
    container_name: jackett
    image: linuxserver/jackett
    restart: unless-stopped
    environment:
      TZ: "America/Detroit"
      AUTO_UPDATE: "TRUE"
      PUID: 1000
      PGID: 1000
    volumes:
      - jackett:/config
      - /media:/downloads
    networks:
      - proxy-traffic

networks:
  proxy-traffic:
    external: true
  lan:
    external: true

volumes:
  utorrent:
    name: utorrent
  nzbget:
    name: nzbget
  radarr:
    name: radarr
  sonarr:
    name: sonarr
  jackett:
    name: jackett
  plex:
    name: plex
  plex-metrics:
    name: plex-metrics
