version: "3"

services:
  plex:
    container_name: plex
    hostname: plex.kangus.net
    image: plexinc/pms-docker:latest
    restart: unless-stopped
    expose:
      - 32400
    environment:
      TZ: "America/Detroit"
      PLEX_CLAIM: ${PLEX_CLAIM}
    volumes:
      - plex:/config
      - plex:/transcode
      - /media:/media
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.plex.entrypoints=web"
      - "traefik.http.routers.plex.rule=Host(`plex.kangus.net`)"
      - "traefik.http.routers.plex.service=plex-service"
      - "traefik.http.services.plex-service.loadbalancer.server.port=32400"
    networks:
      traefik:
      lan:
        ipv4_address: 10.1.7.5

  plex_metrics:
    container_name: plex-metrics
    hostname: plex-metrics
    image: tautulli/tautulli
    restart: unless-stopped
    expose:
      - 80
    environment:
      TZ: "America/Detroit"
    volumes:
      - plex-metrics:/config
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.plex-metrics.entrypoints=web"
      - "traefik.http.routers.plex-metrics.rule=Host(`plex-metrics.kangus.net`)"
      - "traefik.http.routers.plex-metrics.service=plex-metrics-service"
      - "traefik.http.services.plex-metrics-service.loadbalancer.server.port=80"
    networks:
      - traefik

  utorrent:
    container_name: utorrent
    image: ekho/utorrent:legacy
    restart: unless-stopped
    expose:
      - 8080
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      TZ: "America/Detroit"
      PUID: 1000
      PGID: 1000
    volumes:
      - utorrent:/utorrent/settings
      - /media/torrent:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.utorrent.entrypoints=web"
      - "traefik.http.routers.utorrent.rule=Host(`utorrent.kangus.net`)"
      - "traefik.http.routers.utorrent.service=utorrent-service"
      - "traefik.http.services.utorrent-service.loadbalancer.server.port=8080"
    networks:
      traefik:
      lan:
        ipv4_address: 10.1.7.6

  nzbget:
    container_name: nzbget
    image: linuxserver/nzbget
    restart: unless-stopped
    expose:
      - 6789
    environment:
      TZ: "America/Detroit"
      NZBGET_USER: nzbget
      NZBGET_PASS: ${NZBGET_PASS}
      PUID: 1000
      PGID: 1000
    volumes:
      - nzbget:/config
      - /media:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nzbget.entrypoints=web"
      - "traefik.http.routers.nzbget.rule=Host(`nzbget.kangus.net`)"
      - "traefik.http.routers.nzbget.service=nzbget-service"
      - "traefik.http.services.nzbget-service.loadbalancer.server.port=6789"
    networks:
      - traefik

  radarr:
    container_name: radarr
    image: linuxserver/radarr
    restart: unless-stopped
    expose:
      - 7878
    environment:
      TZ: "America/Detroit"
      PUID: 1000
      PGID: 1000
    volumes:
      - radarr:/config
      - /media:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.radarr.entrypoints=web"
      - "traefik.http.routers.radarr.rule=Host(`radarr.kangus.net`)"
      - "traefik.http.routers.radarr.service=radarr-service"
      - "traefik.http.services.radarr-service.loadbalancer.server.port=7878"
    networks:
      - traefik

  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr
    restart: unless-stopped
    expose:
      - 8989
    environment:
      TZ: "America/Detroit"
      PUID: 1000
      PGID: 1000
    volumes:
      - sonarr:/config
      - /media:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sonarr.entrypoints=web"
      - "traefik.http.routers.sonarr.rule=Host(`sonarr.kangus.net`)"
      - "traefik.http.routers.sonarr.service=sonarr-service"
      - "traefik.http.services.sonarr-service.loadbalancer.server.port=8989"
    networks:
      - traefik

  jackett:
    container_name: jackett
    image: linuxserver/jackett
    restart: unless-stopped
    expose:
      - 9117
    environment:
      TZ: "America/Detroit"
      AUTO_UPDATE: "TRUE"
      PUID: 1000
      PGID: 1000
    volumes:
      - jackett:/config
      - /media:/downloads
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jackett.entrypoints=web"
      - "traefik.http.routers.jackett.rule=Host(`jackett.kangus.net`)"
      - "traefik.http.routers.jackett.service=jackett-service"
      - "traefik.http.services.jackett-service.loadbalancer.server.port=9117"
    networks:
      - traefik

networks:
  traefik:
    external: true
  lan:
    external: true

volumes:
  utorrent:
    name: utorrent
  nzbget:
    name: nzbget
  radarr:
    name: radarr
  sonarr:
    name: sonarr
  jackett:
    name: jackett
  plex:
    name: plex
  plex-metrics:
    name: plex-metrics
