version: "3.3"

services:
  traefik:
    image: traefik
    container_name: traefik
    ports:
      - 80:80
      - 443:443
    expose:
      - 8080
    volumes:
      - ssl-certs:/ssl-certs
      - ./etc/traefik:/etc/traefik
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik_https.rule=Host(`traefik.kangus.net`)"
      - "traefik.http.routers.traefik_https.entrypoints=web,websecure"
      - "traefik.http.routers.traefik_https.service=traefik-service"
      - "traefik.http.services.traefik-service.loadbalancer.server.port=8080"
      - "traefik.http.routers.traefik_https.tls=true"
      - "traefik.http.routers.traefik_https.tls.certresolver=production"
networks:
  default:
    name: traefik
volumes:
  ssl-certs:
