version: "3"

services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:2.11.1
    command: -H unix:///var/run/docker.sock
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - proxy-internal

networks:
  proxy-internal:
    external: true

volumes:
  portainer_data:
    external: true
