version: "3"

services:
  dns:
    container_name: dns
    image: pihole/pihole:latest
    restart: always
    environment:
      - TZ=America/New York
    volumes:
      - dns:/etc/pihole
      - dnsmasq:/etc/dnsmasq.d
    expose:
      - 53
      - 80
    depends_on:
      - traefik
    labels:
      - "traefik.enable=true"
      # - "traefik.http.routers.dns-api.rule=Host(`dns.kangus.net`) && Path(`/admin/api.php`)"
      # - "traefik.http.routers.dns-api.tls=true"
      # - "traefik.http.routers.dns-api.tls.certresolver=production"
      # - "traefik.http.routers.dns-api.entrypoints=websecure"
      # - "traefik.http.routers.dns-api.service=dns"
      # - "traefik.http.services.dns-api.loadBalancer.server.port=80"
      - "traefik.http.routers.dns.rule=Host(`dns.kangus.net`)"
      - "traefik.http.routers.dns.tls=true"
      - "traefik.http.routers.dns.tls.certresolver=production"
      - "traefik.http.routers.dns.entrypoints=web,websecure"
      - "traefik.http.routers.dns.service=dns"
      - "traefik.http.services.dns.loadBalancer.server.port=80"
      - "traefik.tcp.routers.dns.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.dns.entrypoints=dns-tcp"
      - "traefik.tcp.routers.dns.service=dns"
      - "traefik.tcp.services.dns.loadbalancer.server.port=53"
      - "traefik.upd.routers.dns.entrypoints=dns-udp"
      - "traefik.udp.routers.dns.service=dns"
      - "traefik.udp.services.dns.loadbalancer.server.port=53"
    networks:
      - traefik
networks:
  traefik:
    external: true
    name: traefik
volumes:
  dns:
    name: dns
  dnsmasq:
    name: dnsmasq
