version: "3"

include:
  - traefik/docker-compose.yml
  - portainer/docker-compose.yml
  - dns/docker-compose.yml

networks:
  traefik:
    name: traefik
  lan:
    name: lan
    driver: macvlan
    driver_opts:
      parent: eno2
    ipam:
      config:
        - subnet: "10.1.7.0/24"
          ip_range: "10.1.7.2/24"
          gateway: "10.1.7.1"
